layout_spectrum: 0.5141669376753271
typography_spectrum: 0.3714686918538064
color:
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  brandStrength: 0.564552583033219
  lightness: 0.8427319922484457
  saturation: 0.5350451793055981
  rhythmicContrast: 0.8981024026870728
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: matthewpiccaver.co.uk
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Dr Matt Piccaver
description: GP and writer
purpose: []
navigation:
  - name: About Me
    id: f876df05-f7fd-4939-a688-923ff34dbb86
    type: content
