name: matthewpiccaver.co.uk
favicon: null
layout_spectrum: 0.60976
typography_spectrum: 0.71541
title: Dr Matt Piccaver
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#36322f'
    - '#dededc'
    - '#b0afaa'
    - '#84817c'
    - '#fefefc'
  brandStrength: 0.5
  lightness: 0.9632389820180833
  saturation: 0.125
  rhythmicContrast: 0.3275401701685041
purpose: []
