name: drmattpiccaver
favicon: null
layout_spectrum: 0.18323669908568263
typography_spectrum: 0.1535327371675521
title: Dr Matt Piccaver
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.29788062651641667
  lightness: 0.9632389820180833
  saturation: 0.1175541311968118
  rhythmicContrast: 0.3275401701685041
purpose: []
