name: matthewpiccaver.co.uk
favicon: null
layout_spectrum: 0.5122
typography_spectrum: 0.50403
title: Dr Matt Piccaver
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#36322f'
    - '#dededc'
    - '#b0afaa'
    - '#84817c'
    - '#fefefc'
  brandStrength: 0
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
