name: drmattpiccaver
favicon: null
layout_spectrum: 0.18323669908568263
typography_spectrum: 0.1535327371675521
title: Dr Matt Piccaver
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#010101'
    - '#5e3927'
    - '#3661d4'
    - '#68aac6'
  brandStrength: 0.5
  lightness: 0.9632389820180833
  saturation: 0.1875
  rhythmicContrast: 0.3275401701685041
purpose: []
