name: matthewpiccaver.co.uk
favicon: null
layout_spectrum: 0.74707
typography_spectrum: 0.50403
title: Dr Matt Piccaver
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#c1cbca'
    - '#000407'
    - '#814231'
    - '#64b863'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
